-- HalimiSOC initial schema.
--
-- Conventions applied throughout:
--   * every timestamp is TIMESTAMPTZ and written in UTC;
--   * identifiers are TEXT ULIDs generated by the application, not sequences,
--     so an id can be formed before the row exists and used as an idempotency
--     key;
--   * delete behaviour is explicit on every foreign key;
--   * JSONB is used only for bounded, read-as-a-whole collections (evidence id
--     lists, attributes), never for fields that are filtered on.

CREATE TABLE IF NOT EXISTS schema_migrations (
    version     TEXT PRIMARY KEY,
    applied_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Operators. The password hash is an Argon2id PHC string; no plaintext or
-- reversible material is stored anywhere.
CREATE TABLE IF NOT EXISTS users (
    id             TEXT PRIMARY KEY,
    username       TEXT NOT NULL,
    password_hash  TEXT NOT NULL,
    role           TEXT NOT NULL CHECK (role IN ('ADMIN', 'ANALYST', 'READONLY')),
    disabled       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ NOT NULL,
    last_login_at  TIMESTAMPTZ
);

-- Usernames are compared case-insensitively, so the uniqueness constraint must
-- be case-insensitive too.
CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower_idx ON users (lower(username));

-- Server-side sessions. Storing the session server-side is what makes
-- revocation immediate; a stateless signed cookie could not be withdrawn.
CREATE TABLE IF NOT EXISTS sessions (
    id            TEXT PRIMARY KEY,
    user_id       TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash    TEXT NOT NULL,
    csrf_token    TEXT NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL,
    expires_at    TIMESTAMPTZ NOT NULL,
    last_seen_at  TIMESTAMPTZ NOT NULL,
    revoked_at    TIMESTAMPTZ,
    source_ip     TEXT,
    user_agent    TEXT
);

CREATE INDEX IF NOT EXISTS sessions_user_idx ON sessions (user_id);
CREATE INDEX IF NOT EXISTS sessions_expires_idx ON sessions (expires_at);

-- Enrolled collection endpoints.
CREATE TABLE IF NOT EXISTS agents (
    id              TEXT PRIMARY KEY,
    host            TEXT NOT NULL,
    os              TEXT,
    version         TEXT,
    status          TEXT NOT NULL CHECK (status IN ('ONLINE', 'OFFLINE', 'DEGRADED', 'UNKNOWN')),
    enrolled_at     TIMESTAMPTZ NOT NULL,
    last_heartbeat  TIMESTAMPTZ,
    revoked_at      TIMESTAMPTZ,
    queue_depth     BIGINT NOT NULL DEFAULT 0,
    spool_bytes     BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS agents_host_idx ON agents (host);

-- Agent credentials. Only the SHA-256 hash of a token is stored, so a database
-- disclosure does not yield usable credentials.
CREATE TABLE IF NOT EXISTS agent_tokens (
    id           TEXT PRIMARY KEY,
    agent_id     TEXT NOT NULL REFERENCES agents (id) ON DELETE CASCADE,
    token_hash   TEXT NOT NULL,
    prefix       TEXT NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL,
    last_used_at TIMESTAMPTZ,
    rotated_at   TIMESTAMPTZ,
    revoked_at   TIMESTAMPTZ,
    expires_at   TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS agent_tokens_hash_idx ON agent_tokens (token_hash);
CREATE INDEX IF NOT EXISTS agent_tokens_agent_idx ON agent_tokens (agent_id);

-- Canonical security events.
--
-- event_time is the source-reported occurrence time; received_at is the trusted
-- server receipt time. They are separate columns because conflating them would
-- let an agent's clock rewrite the server's view of when something happened.
CREATE TABLE IF NOT EXISTS events (
    id              TEXT PRIMARY KEY,
    schema_version  TEXT NOT NULL,
    type            TEXT NOT NULL,
    event_time      TIMESTAMPTZ NOT NULL,
    received_at     TIMESTAMPTZ NOT NULL,
    observed_at     TIMESTAMPTZ,
    host            TEXT NOT NULL,
    agent_id        TEXT REFERENCES agents (id) ON DELETE SET NULL,
    source          TEXT NOT NULL,
    source_path     TEXT,
    actor           TEXT,
    target          TEXT,
    src_ip          TEXT,
    src_port        INTEGER,
    dst_ip          TEXT,
    dst_port        INTEGER,
    protocol        TEXT,
    outcome         TEXT,
    severity        TEXT NOT NULL,
    attributes      JSONB NOT NULL DEFAULT '{}'::jsonb,
    message         TEXT,
    raw             TEXT,
    raw_expired     BOOLEAN NOT NULL DEFAULT FALSE,
    dedupe_key      TEXT NOT NULL DEFAULT ''
);

-- The primary read pattern is "newest first, stable tie-break", so the index
-- matches the ORDER BY exactly.
CREATE INDEX IF NOT EXISTS events_time_idx ON events (event_time DESC, id DESC);
CREATE INDEX IF NOT EXISTS events_host_idx ON events (host, event_time DESC);
CREATE INDEX IF NOT EXISTS events_actor_idx ON events (actor, event_time DESC);
CREATE INDEX IF NOT EXISTS events_src_ip_idx ON events (src_ip, event_time DESC);
CREATE INDEX IF NOT EXISTS events_type_idx ON events (type, event_time DESC);

-- Advisory, deliberately not unique: two genuinely distinct log lines can share
-- a dedupe key (identical message in the same second). The event id remains the
-- authoritative idempotency key.
CREATE INDEX IF NOT EXISTS events_dedupe_idx ON events (dedupe_key);

-- Deterministic detections. rule_id and rule_version are stored on every alert
-- so historical detection stays explainable after a rule changes.
CREATE TABLE IF NOT EXISTS alerts (
    id            TEXT PRIMARY KEY,
    rule_id       TEXT NOT NULL,
    rule_version  INTEGER NOT NULL,
    rule_name     TEXT NOT NULL,
    severity      TEXT NOT NULL,
    status        TEXT NOT NULL CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED')),
    title         TEXT NOT NULL,
    reason        TEXT NOT NULL,
    host          TEXT,
    actor         TEXT,
    src_ip        TEXT,
    entity        TEXT,
    event_ids     JSONB NOT NULL DEFAULT '[]'::jsonb,
    count         INTEGER NOT NULL,
    window_start  TIMESTAMPTZ NOT NULL,
    window_end    TIMESTAMPTZ NOT NULL,
    dedupe_key    TEXT NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS alerts_created_idx ON alerts (created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS alerts_status_idx ON alerts (status);
CREATE INDEX IF NOT EXISTS alerts_severity_idx ON alerts (severity);
CREATE INDEX IF NOT EXISTS alerts_host_idx ON alerts (host);
CREATE INDEX IF NOT EXISTS alerts_rule_idx ON alerts (rule_id, rule_version);

-- Correlated incidents. The nested collections are bounded by the correlation
-- engine before they are written, so JSONB stays a reasonable choice.
CREATE TABLE IF NOT EXISTS incidents (
    id          TEXT PRIMARY KEY,
    title       TEXT NOT NULL,
    summary     TEXT NOT NULL DEFAULT '',
    severity    TEXT NOT NULL,
    status      TEXT NOT NULL CHECK (status IN ('OPEN', 'INVESTIGATING', 'CONTAINED', 'RESOLVED', 'CLOSED')),
    hosts       JSONB NOT NULL DEFAULT '[]'::jsonb,
    actors      JSONB NOT NULL DEFAULT '[]'::jsonb,
    alert_ids   JSONB NOT NULL DEFAULT '[]'::jsonb,
    event_ids   JSONB NOT NULL DEFAULT '[]'::jsonb,
    stages      JSONB NOT NULL DEFAULT '[]'::jsonb,
    first_seen  TIMESTAMPTZ NOT NULL,
    last_seen   TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS incidents_last_seen_idx ON incidents (last_seen DESC, id DESC);
CREATE INDEX IF NOT EXISTS incidents_status_idx ON incidents (status);
CREATE INDEX IF NOT EXISTS incidents_severity_idx ON incidents (severity);

-- Audit records. This is protected application storage, not claimed
-- tamper-proof forensic storage.
CREATE TABLE IF NOT EXISTS audit_logs (
    id          TEXT PRIMARY KEY,
    actor       TEXT NOT NULL,
    action      TEXT NOT NULL,
    resource    TEXT NOT NULL,
    resource_id TEXT,
    result      TEXT NOT NULL,
    timestamp   TIMESTAMPTZ NOT NULL,
    source_ip   TEXT,
    detail      TEXT
);

CREATE INDEX IF NOT EXISTS audit_timestamp_idx ON audit_logs (timestamp DESC, id DESC);
CREATE INDEX IF NOT EXISTS audit_actor_idx ON audit_logs (actor);
CREATE INDEX IF NOT EXISTS audit_action_idx ON audit_logs (action);
