// Package alerts defines the deterministic alert contract.
//
// An alert is produced by the detection engine, never by AI and never from a
// client-supplied severity. The fields here are the evidence an analyst needs
// to understand why a rule fired.
package alerts

import (
	"fmt"
	"time"

	"github.com/halimi/halimisoc/internal/events/model"
)

// Status is the alert lifecycle state.
type Status string

const (
	StatusOpen         Status = "OPEN"
	StatusAcknowledged Status = "ACKNOWLEDGED"
	StatusResolved     Status = "RESOLVED"
	StatusDismissed    Status = "DISMISSED"
)

// StatusSet is the closed set of alert statuses.
var StatusSet = []Status{StatusOpen, StatusAcknowledged, StatusResolved, StatusDismissed}

// Valid reports whether s is a canonical alert status.
func (s Status) Valid() bool {
	for _, v := range StatusSet {
		if v == s {
			return true
		}
	}
	return false
}

// Terminal reports whether the status ends the alert's active life.
func (s Status) Terminal() bool {
	return s == StatusResolved || s == StatusDismissed
}

// Alert is a single deterministic detection outcome.
type Alert struct {
	ID string `json:"id"`

	// RuleID and RuleVersion identify the exact rule revision that fired.
	// Historical alerts must remain explainable after a rule changes.
	RuleID      string `json:"rule_id"`
	RuleVersion int    `json:"rule_version"`
	RuleName    string `json:"rule_name"`

	// Severity is the rule's deterministic severity. It is never derived from
	// the event's source-declared severity, the client, or a model.
	Severity model.Severity `json:"severity"`

	Status Status `json:"status"`

	// Title and Reason are human-readable, generated by the engine from
	// validated values, not by interpolating raw telemetry.
	Title  string `json:"title"`
	Reason string `json:"reason"`

	// Entity context used for correlation.
	Host     string `json:"host,omitempty"`
	Actor    string `json:"actor,omitempty"`
	SourceIP string `json:"source_ip,omitempty"`
	Entity   string `json:"entity,omitempty"`

	// EventIDs are the evidence events that contributed to this alert.
	EventIDs []string `json:"event_ids"`

	// Count is the number of qualifying events observed in the window.
	Count int `json:"count"`

	// WindowStart and WindowEnd bound the detection window.
	WindowStart time.Time `json:"window_start"`
	WindowEnd   time.Time `json:"window_end"`

	// DedupeKey makes alert suppression deterministic across replays.
	DedupeKey string `json:"dedupe_key"`

	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Validate checks the alert invariants that must hold before persistence.
func (a *Alert) Validate() error {
	if a.ID == "" {
		return fmt.Errorf("alert id is required")
	}
	if a.RuleID == "" {
		return fmt.Errorf("alert rule_id is required")
	}
	if a.RuleVersion <= 0 {
		return fmt.Errorf("alert rule_version must be positive")
	}
	if model.SeverityRank(a.Severity) == 0 {
		return fmt.Errorf("alert severity %q is not canonical", a.Severity)
	}
	if !a.Status.Valid() {
		return fmt.Errorf("alert status %q is not canonical", a.Status)
	}
	if len(a.EventIDs) == 0 {
		return fmt.Errorf("alert must reference at least one evidence event")
	}
	return nil
}

// Transition describes an allowed alert status change.
type Transition struct {
	From Status
	To   Status
}

// allowedTransitions is the alert state machine.
//
// An alert may be acknowledged, then resolved or dismissed. It may also be
// dismissed straight from OPEN when an analyst immediately recognises a false
// positive. Reopening a terminal alert is deliberately not allowed: a new
// qualifying detection creates a new alert instead, which keeps the audit trail
// linear and prevents an old alert from silently changing meaning.
var allowedTransitions = map[Transition]bool{
	{StatusOpen, StatusAcknowledged}:      true,
	{StatusOpen, StatusResolved}:          true,
	{StatusOpen, StatusDismissed}:         true,
	{StatusAcknowledged, StatusResolved}:  true,
	{StatusAcknowledged, StatusDismissed}: true,
}

// CanTransition reports whether a status change is permitted.
func CanTransition(from, to Status) bool {
	if from == to {
		return false
	}
	return allowedTransitions[Transition{From: from, To: to}]
}
